name: setup
author: nazar
description: setup

inputs:
  go-version-file:
    description: "Go version to install"
    default: "go.mod"
    required: false

  install-goose:
    description: "Option to install goose or not"
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Install Goose
      shell: sh
      if: ${{ inputs.install-goose  == 'true' }}
      run: go install github.com/pressly/goose/v3/cmd/goose@latest
