services:
  smtp_mock:
    image: mailhog/mailhog
    container_name: smtp_mock
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
        - test_network
#  weather-service-test:
#    build:
#      context: .
#      dockerfile: ./weather/Dockerfile
#    platform: linux/amd64
#    restart: on-failure
#    container_name: weather-service-test
#    ports:
#      - "50052:50052"
#    environment:
#      - WEATHER_API_URL=
#    networks:
#      - test_network



volumes:
  redis-data:

networks:
  test_network:
    driver: bridge