version: '3'


dotenv:
  - .env

tasks:

  run:
    desc: "Run service"
    cmds:
      - docker-compose up -d

  stop:
    desc: "Stop service"
    cmds:
      - docker-compose down


  lint:
    desc: "Run golangci-lint"
    deps:
      - install:lint
    preconditions:
      - command -v golangci-lint
    cmds:
      - golangci-lint run --config <(curl -sSfL https://raw.githubusercontent.com/fabl3ss/genesis-se-school-linter/refs/heads/main/.golangci.yaml) --modules-download-mode=readonly

  install:
    desc: "Install all packages"
    deps:
      - install:lint

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint
  install:goose:
    desc: "Install goose"
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest
    status:
      - command -v goose


  migrations-up:
    desc: "Start migrations for db"
    cmds:
      - goose -dir migrations sqlite3 subscriptions.db up

  migrations-down:
    desc: "Rollback migration"
    cmds:
      - goose -dir migrations sqlite3 subscriptions.db down

  migrations-status:
    desc: "Show migration status"
    cmds:
      - goose -dir migrations sqlite3 subscriptions.db status


