version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all
  run:
    desc: "Populate env from .env file and run service"
    deps: [install:godotenv]
    cmds:
      - godotenv -f ../.env task run-with-env

  install:
    desc: "Install all tools"
    deps:
      - install:lint
      - install:gofumpt
      - install:mock

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  install:gofumpt:
    desc: "Install gofumpt"
    cmds:
      - go install mvdan.cc/gofumpt@latest
    status:
      - command -v gofumpt

  install:godotenv:
    desc: "Install go dot env lib"
    cmds:
      - go install github.com/joho/godotenv/cmd/godotenv@latest
    status:
      - command godotenv

  gen:swagger:
    desc: "Generate swagger docs"
    dir: ./main
    cmds:
      - swag init --parseDependency --parseInternal -g /main.go --output ../docs