version: "3"

tasks:
  run:
    desc: "Populate env from .env file and run service"
    deps: [install:godotenv]
    cmds:
      - godotenv -f ../.env task run-with-env

  lint:
    desc: "Run golangci-lint"
    deps:
      - install:lint
    preconditions:
      - command -v golangci-lint
    cmds:
      - golangci-lint run --config <(curl -sSfL https://raw.githubusercontent.com/fabl3ss/genesis-se-school-linter/refs/heads/main/.golangci.yaml) --modules-download-mode=readonly

  install:
    desc: "Install all tools"
    deps:
      - install:lint


  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  test:unit:
    desc: "Run unit tests"
    cmds:
      - go test -v -tags=unit ./...

  test:integration:
    desc: "Run integration tests (requires docker-compose.test.yml)"
    dotenv:
      - .env.example
    cmds:
      - docker compose -f docker-compose.test.yml up -d
      - sleep 2
      - go test -v -tags=integration ./...
      - docker compose -f docker-compose.test.yml down
