name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Download Go modules
        run: |
            go mod tidy
            go mod download
            go mod vendor

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run Linter
        run: task lint


  migrate-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run DB migrations
        run: task migrations-up