name: CI

on:
  push:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: .github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-swaggo: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run Swag
        run: swag init --parseDependency --parseInternal --output ../docs -g ./main.go
        working-directory: ./main

      - name: Run Linter
        run: task lint


  migrate-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-goose: 'true'

      - name: Run DB migrations
        run: task migrations-up

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-swaggo: 'true'

      - name: run Swag
        run: swag init --parseDependency --parseInternal --output ../docs -g ./main.go
        working-directory: ./main

      - name: Run Unit Tests
        run: task test:unit

  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-goose: 'true'
          install-swaggo: 'true'

      - name: run Swag
        run: swag init --parseDependency --parseInternal --output ../docs -g ./main.go
        working-directory: ./main

      - name: Run Integration Tests
        run: task test:integration
