name: CI

on:
  push:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-swaggo: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: run Swag
        run: swag init --parseDependency --parseInternal --output ./docs -g ./main/main.go

      - name: Run Linter
        run: task lint


  migrate-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        uses: ./.github/actions/setup
        with:
          go-version-file: 'go.mod'
          install-goose: 'true'

      - name: Run DB migrations
        run: task migrations-up