name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        run: task lint


  migrate-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DB migrations
        run: task migrations-up